Controllers/AlunosController.cs
using Microsoft.AspNetCore.Mvc;
using Ex_data_base_com_seção.Models;
//PACOTE DA FUNÇÃO SEÇÃO DE USUÁRIO
using Microsoft.AspNetCore.Http;
namespace Ex_data_base_com_seção.Controllers
{
    public class AlunosController : Controller
    {
        public IActionResult Cadastrar()
        {
            return View();
        }

        // Controller >> Views >> Controller >> Model
        [HttpPost] //RECEBENDO VALORES DE Cadastrar EM Views
        public IActionResult Cadastrar(Alunos a)
        {
            //CRIANDO OBJETO DA CLASSE AlunosRepository
            AlunosRepository ar = new AlunosRepository();
            //INSTANCIANDO A FUNÇÃO Inserir DE Model
            ar.Inserir(a); //PASSANDO OS OBJETOS DE Cadastrar EM Views PARA A FUNÇÃO Inserir EM Model POR PARÂMETRO
            return View();
        }

        //ESSA PAGINA APARECE SÓ QUANDO O USUÁRIO ESTIVER LOGADO
        public IActionResult Listar()
        {
            // SE O USUÁRIO NÃO ESTIVER LOGADO SERÁ REDIRECIONADO PARA Login EM Views
            if(HttpContext.Session.GetInt32("IdUsuario") == null)
            {
                return RedirectToAction("Login");
            }
            AlunosRepository ar = new AlunosRepository();
            return View(ar.Listar());//PASSANDO A LISTA DE Listar EM Model POR PARÂMETRO PARA Listar EM Views
        }
        public IActionResult Editar(int Id)
        {
            AlunosRepository ar = new AlunosRepository();
            return View(ar.BuscaPorId(Id));
        }
        [HttpPost]
        public IActionResult Editar(Alunos a)
        {
            AlunosRepository ar = new AlunosRepository();
            ar.Editar(a);
            return RedirectToAction("Listar");
        }

        public IActionResult Excluir(int Id)//Usando O "/Alunos/Excluir?Id=@a.IdAlunos" DE Listar EM Views
        {
            AlunosRepository ar = new AlunosRepository();
            ar.Deletar(Id);
            return RedirectToAction("Listar");//APÓS A FUNÇÃO SER EXECUTADA SERA REDIRECIONADA PARA Listar EM Views
        }
        public IActionResult Login()
        {
            return View();
        }
        //VALIDANDO SEÇÃO
        [HttpPost]
        public IActionResult Login(Alunos a)
        {
            AlunosRepository ar = new AlunosRepository();
            Alunos usuario = ar.ValidarLogin(a); //usuario RECEBE Alunos POR PARÂMETRO
            if(usuario == null) //VERIFICANDO SE O USUÁRIO É NULO
            {
                return View();
            }
            else
            {
                HttpContext.Session.SetInt32("IdUsuario",usuario.IdAluno); //SEÇÃO É UM REGISTRO DE ACESSO
                HttpContext.Session.SetString("usuario",usuario.Usuario); //SEÇÃO É UM REGISTRO DE ACESSO

                //int IdUsuario = (int)HttpContext.Session.GetInt32("IdAluno"); //CAPTURA DE ID DO USUARIO LOGADO PARA INSERÇÃO NO BANCO DE DADOS

                return RedirectToAction("Listar");//SE O USUÁRIO E SENHA ESTIVER CORRETO SERÁ REDIRECIONADO PARA A PAGINA LISTAR
            }
            
        }
    }
}

Views/Shared/_Layout.cshtml
<!-- PACOTE PARA USAR A FUNÇÃO if(Context.Session.GetInt32 -->
@using Microsoft.AspNetCore.Http;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ex_data_base_com_seção</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Ex_data_base_com_seção</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <!-- PAGINAS QUE VÃO APARECER QUANDO O USUÁRIO NÃO ESTIVER LOGADO -->
                        @if(Context.Session.GetInt32("IdUsuario") == null) //INFORMAÇÃO QUE VEM DA FUNÇÃO public IActionResult Login(Alunos a)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Alunos" asp-action="Login">Login</a>
                            </li>
                        }
                        else
                        {
                            //PAGINAS QUE VÃO APARECER SÓ QUANDO O USUÁRIO ESTIVER LOGADO
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Alunos" asp-action="Cadastrar">Cadastrar</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Alunos" asp-action="Listar">Lista</a>
                            </li>
                        }
                    </ul>
                    <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ViewsProjeto" asp-action="Create">Criar anotação</a>
                    </li>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Ex_data_base_com_seção - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>